- name: "type: mod request"
  description: "Request for a mod to be added"
  color: "2c4175"
- name: "type: bug report"
  description: "Report a bug"
  color: "ae120d"
- name: "type: feature request"
  description: "Request a feature to be added"
  color: "20dca9"
- name: "status: needs testing"
  description: "This bugfix needs to be tested"
  color: "900C3F"
- name: "status: blocked"
  description: "This issue or PR is blocked"
  color: "763C28"
- name: "bug: unverified"
  description: "This bug report still needs to be verified"
  color: "750606"
- name: "bug: confirmed"
  description: "This bug report has been verified"
  color: "670a0a"
- name: "modpack: fullmash"
  description: "This issue or PR is related to the fullmash modpack"
  color: "f0a500"
- name: "modpack: pixelmon-with-create"
  description: "This issue or PR is related to the pixelmon-with-create modpack"
  color: "f0a500"
