name: Feature Request
description: "Submit a request for a feature to be added to the server."
assignees: ["jaronz"]
labels: ["type: feature request"]
title: "[FEAT] "

body:
  - type: textarea
    attributes:
      label: Feature
      description: Describe the feature
    validations:
      required: true

  - type: input
    attributes:
      label: Modpack
      description: To which modpack(s) should this feature be added?
      placeholder: "Fullmash / LumioseCraft"
    validations:
      required: true
