hash-format = "sha256"

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "efb8a4921c466e737afaa484eca9aedc55c4be1d5647a3b447f961d66482faaf"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "f3e80a5b8992883cdad15ec2e431152ae67c48db3a131a7b1b5ce705da3f89f2"
metafile = true
