name = "Temp"
author = "Jaron Zijlstra"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc5154473ef82043e856ab8aeaf7d82408fa841a3879a8ca1ba6a190dba8ea84"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
