name = "LumioseCraft"
author = "Jaron Zijlstra"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abed136e370f6573b49c86b2fcf1214a45fd3597e13400a3d7f7b91dbc162874"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
