name = "LumioseCraft"
author = "Jaron Zijlstra"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "044d0d0fe3fe3faf6d68ad3029477b1879b50fe934b3974b120509b088afb057"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
