name = "LumioseCraft"
author = "Jaron Zijlstra"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cc97044ea170c95f4f8e49bead04309a8f259dc9e41e656237bd3bff27c8843"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.145"
